name: Manual CI

on: [push]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
        cache: sbt
    - name: Setup sbt
      uses: sbt/setup-sbt@v1
    - name: Run tests
      run: sbt test
